# Generated by Django 4.2 on 2024-08-30 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('location', models.CharField(choices=[('USA', 'USA'), ('UK', 'UK'), ('Canada', 'Canada')], default='USA', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Not shown but required', max_length=255)),
                ('balance', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('Info', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=255)),
                ('dob', models.CharField(blank=True, max_length=255)),
                ('Status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('created',),
            },
        ),
    ]
