# Generated by Django 4.2 on 2025-04-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_bank_product_bin_product_country_product_exp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='location',
            field=models.CharField(choices=[('USA', 'USA'), ('UK', 'UK'), ('Canada', 'Canada'), ('Other', 'Other')], default='USA', max_length=255),
        ),
    ]
